#!/bin/sh

#
# Wait for user input
#

echo Timeout in 3 seconds...
echo -e "Do you want to skip or not? (y or n are valid):"
read ans
ans=`echo $ans | tr "[A-Z]" "[a-z]"`
if [ "$ans" = "y" ]
then
  exit 1
else
  exit 2
fi
